## CHANGE this to the name of your plugin.
name: SlimyLoot

## CHANGE this to your username.
author: NCBPFluffyBear

## CHANGE this to a meaninful but short description of your plugin.
description: A Slimefun addon that adds Slimefun drops

## CHANGE this to the path of the class that extends JavaPlugin.
main: io.ncbpfluffybear.slimyloot.SlimyLoot

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/NCBPFluffyBear/SlimyLoot

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

commands:
    slimyloot:
        description: Command for the SlimyLoot addon

permissions:
    slimyloot.loot.kill:
        description: Allows you to get items from killing mobs
        default: true
    slimyloot.loot.fish:
        description: Allows you to get items from fishing
        default: true
    slimyloot.loot.break:
        description: Allows you to get items from breaking blocks
        default: true
    slimyloot.admin:
        description: Allows you to use SlimyLoot admin commands
        default: op
